//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Fallas_IMSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMSSEntities : DbContext
    {
        public IMSSEntities()
            : base("name=IMSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areas_imss> areas_imss { get; set; }
        public virtual DbSet<existencias> existencias { get; set; }
        public virtual DbSet<fallas> fallas { get; set; }
        public virtual DbSet<hospitales_imss> hospitales_imss { get; set; }
        public virtual DbSet<material_estados> material_estados { get; set; }
        public virtual DbSet<materiales> materiales { get; set; }
        public virtual DbSet<operacion> operacion { get; set; }
        public virtual DbSet<reporte> reporte { get; set; }
        public virtual DbSet<reporte_fallas> reporte_fallas { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tipo_hardware> tipo_hardware { get; set; }
        public virtual DbSet<tipos_falla> tipos_falla { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
