//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Fallas_IMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fallas
    {
        public int Id_falla { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> Id_tipo_falla { get; set; }
    
        public virtual tipos_falla tipos_falla { get; set; }
    }
}
