//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Fallas_IMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte_fallas
    {
        public int Id_reporte_falla { get; set; }
        public int id_reporte { get; set; }
        public Nullable<int> id_falla { get; set; }
        public string falla { get; set; }
    
        public virtual reporte reporte { get; set; }
    }
}
